import {Component, OnInit} from '@angular/core';
import {DomSanitizer} from '@angular/platform-browser';

@Component({
  selector: 'app-portfolio-detail',
  templateUrl: './portfolio-detail.component.html',
  styleUrls: ['./portfolio-detail.component.scss']
})
export class PortfolioDetailComponent implements OnInit {

  properties: any[];
  notes: any[];
  forms: string;

  constructor(private sanitizer: DomSanitizer) {
  }

  ngOnInit() {
    this.properties = [
      {
        id: 0,
        status: 'red',
        street: '1541 Linwood Ave',
        city: 'Columbus',
        state: 'OH',
        zipCode: '43207',
        dateDue: '08/20/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 1,
        status: 'red',
        street: '10825 Royalton Rd',
        city: 'Amanda',
        state: 'OH',
        zipCode: '43102',
        dateDue: '08/20/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 2,
        status: 'red',
        street: '805 Rosemore Ave',
        city: 'Whitehall',
        state: 'OH',
        zipCode: '43213',
        dateDue: '08/20/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 3,
        status: 'red',
        street: '294 S Ohio Dr',
        city: 'Columbus',
        state: 'OH',
        zipCode: '43205',
        dateDue: '08/21/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 4,
        status: 'red',
        street: '23464 State Route 141',
        city: 'Lawrence',
        state: 'OH',
        zipCode: '45688',
        dateDue: '08/21/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 5,
        status: 'red',
        street: '495 W Broad St',
        city: 'Columbus',
        state: 'OH',
        zipCode: '43215',
        dateDue: '08/22/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 6,
        status: 'yellow',
        street: '4635 Paxton Dr S',
        city: 'Hilliard',
        state: 'OH',
        zipCode: '43026',
        dateDue: '08/23/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 7,
        status: 'yellow',
        street: '2078 Langham Rd',
        city: 'Upper Arlington',
        state: 'OH',
        zipCode: '43221',
        dateDue: '08/23/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 8,
        status: 'yellow',
        street: '96 W Lincoln Ave',
        city: 'Worthington',
        state: 'OH',
        zipCode: '43085',
        dateDue: '08/24/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 9,
        status: 'yellow',
        street: '1970 Cardigan Ave',
        city: 'Marble Cliff',
        state: 'OH',
        zipCode: '43212',
        dateDue: '08/24/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 10,
        status: 'green',
        street: '7061 Schneider Way',
        city: 'Jefferson Township',
        state: 'OH',
        zipCode: '43004',
        dateDue: '08/25/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 11,
        status: 'green',
        street: '1151 Bayridge Dr',
        city: 'Orange Township',
        state: 'OH',
        zipCode: '43035',
        dateDue: '08/26/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 12,
        status: 'green',
        street: '197 W Park St',
        city: 'Westerville',
        state: 'OH',
        zipCode: '43081',
        dateDue: '08/27/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
      {
        id: 13,
        status: 'green',
        street: '7690 Hilliard Ct',
        city: 'Canal Winchester',
        state: 'OH',
        zipCode: '43110',
        dateDue: '08/28/2019',
        unit: '',
        enableStep: false,
        steps: {
          step1: false,
          step2: false,
          step3: false,
          step4: false,
          step5: false,
          step6: false,
        },
      },
    ];
    this.notes = [
      {
        avatar: '',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        date: 'August 28, 2019 - 2:13 PM',
      },
      {
        avatar: '',
        content: 'Ut enim ad minim veniam, quis nostrud exercitation.',
        date: 'August 27, 2019 - 6:15 PM',
      },
      {
        avatar: '',
        content: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu.',
        date: 'August 27, 2018 - 8:16 AM',
      },
      {
        avatar: '',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        date: 'August 28, 2019 - 2:13 PM',
      },
      {
        avatar: '',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        date: 'August 28, 2019 - 2:13 PM',
      },
      {
        avatar: '',
        content: 'Ut enim ad minim veniam, quis nostrud exercitation.',
        date: 'August 27, 2019 - 6:15 PM',
      },
      {
        avatar: '',
        content: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu.',
        date: 'August 27, 2018 - 8:16 AM',
      },
      {
        avatar: '',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        date: 'August 28, 2019 - 2:13 PM',
      },
      {
        avatar: '',
        content: 'Ut enim ad minim veniam, quis nostrud exercitation.',
        date: 'August 27, 2019 - 6:15 PM',
      },
      {
        avatar: '',
        content: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu.',
        date: 'August 27, 2018 - 8:16 AM',
      },
    ];
    this.forms = 'https://www.mcs360.com/documents/compliancedoc/VPR/Northwood%20OH%20%20Vacant%20Property%20Registration%20Form.pdf';
  }

}
