#!/bin/bash

# Before building, this needs to be invoked:    $scl enable rh-nodejs10 bash

date
printf '\n--- BEGIN: build'

# ------------------------------------------------------------------------------
printf '\n$node --version'
node --version

printf '\n$npm --version'
npm --version

# ------------------------------------------------------------------------------
cd $HOME/repos/mpi-proc-ang
printf '\n$pwd'
pwd

printf '\n$rm -rf dist'
rm -rf dist

# ------------------------------------------------------------------------------
export NODE_OPTIONS=--max_old_space_size=4096

printf '\n$npm install'
npm install

printf '\n$ng build --proc'
ng build --prod

# ------------------------------------------------------------------------------
popd
printf '\nEND: build'
date
