#!/bin/bash
printf '\nbegin build'
date
pwd
pushd .
cd ../..
rm -rf dist
ls dist

printf '\nbuilding project'
pwd

export NODE_OPTIONS=--max_old_space_size=4096
npm install
ng build --prod

# return
popd
pwd
printf '\nend build'
date
